name: 01tfa action

on:
  schedule:
    - cron: '07 */3 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "01tfa bot"
      
      - name: updating 01tfa
        run: sh ${GITHUB_WORKSPACE}/ressources/btv/py/01tfa.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "01tfa updated"
          git push
