name: 0tm

on:
  schedule:
    - cron: '29 */3 * * *'
  push:
    branches:
      - main
      
  workflow_dispatch:
  
jobs:
  inject_replace:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout freeiptv
        uses: actions/checkout@v3
        
      - name: Fetch Content
        id: fetch_content
        env:
          PRIVATE_REPO_TOKEN: ${{ secrets.PRIVATE_REPO_TOKEN }}
        run: |
          content=$(curl -H "Authorization: token $PRIVATE_REPO_TOKEN" -H "Accept: application/vnd.github.v3.raw" "https://raw.githubusercontent.com/ipstreet312/myrep/main/ressources/0tmc.m3u8")
          echo "content=$content" >> $GITHUB_OUTPUT

      - name: Replace Text
        run: |
          sed -i "/tmc-cmaf/ c $(echo '${{ steps.fetch_content.outputs.content }}')" all.m3u
    
      - name: Commit and Push Changes
        run: |
          git config --local user.name "0tm Action"
          git config user.email "<>"
          git add all.m3u
          git commit -m "0tm updated"
          git push
