name: cnnturk

on:
  schedule:
    - cron: '05 */3 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "cnnturk bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests streamlink

      #- name: Install streamlink module from forked repository
      #  run: python3 -m pip install git+https://github.com/ipstreet312/streamlink

      - name: fetch content cnnturk
        run: |
          python3 ressources/tur/cnnturk.py > ressources/tur/cnnturk.m3u8

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git commit -m "cnnturk updated"
          git push
