name: eqpetv7 action

on:
  schedule:
    - cron: '00 7 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "eqpetv7 bot"
      
      - name: updating eqpetv7
        run: python3 ${GITHUB_WORKSPACE}/ressources/dmotion/py/eqpe/eqpetv.py > ${GITHUB_WORKSPACE}/ressources/dmotion/py/eqpe/eqpetv.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "eqpetv7 updated"
          git push
