name: espsor1 action

on:
  schedule:
    - cron: '0 0 * * *'
  
  workflow_dispatch:

jobs:
  runscript:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "espsor1 bot"
      
      - name: updating espsor1
        run: sh ressources/extr/py/espsor1.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "espsor1 updated"
          git push