name: frjo24 action

on:
  schedule:
    - cron: '35 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "frjo24 bot"
      
      - name: updating fr2nv
        run: |
          python3 ressources/ftv/py/frjo24.py > ressources/ftv/py/frjo24.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "frjo24 updated"
          git push
