name: frrge action

on:
  schedule:
    - cron: '33 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "frrge bot"
      
      - name: updating fr2nv
        run: |
          python3 ressources/ftv/py2/rge1.py > ressources/ftv/py2/rge1.m3u8 &&
          python3 ressources/ftv/py2/rge2.py > ressources/ftv/py2/rge2.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "frrge updated"
          git push
