name: gnrcdm

on:
  schedule:
    - cron: '56 */4 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "gnrcdm bot"
      
      - name: grab m3u files
        run: |
          pwd
          cd ./ressources/dmotion/py/gnrcpltfrm
          python3 gnrcpltfrm.py "x21oo10" > fbtv.m3u8
          python3 gnrcpltfrm.py "x8egnb8" > portoc.m3u8
          echo "m3u grabbed"
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "gnrcdm updated"
          git push
