name: k12 action

on:
  schedule:
    - cron: '05 */20 * * *'
  
  workflow_dispatch:

jobs:
  runscript:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
      
      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "k12 bot"
      
      - name: updating k12
        run: sh ressources/keshetil/py/k12.sh
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git commit -m "k12 updated"
          git push
