# Thanks to LITUATUI user on github
name: nessma action
on:
  schedule:
    - cron: "40 */5 * * *"
  
  workflow_dispatch:

jobs:
  Update-streams:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: updating nessma
        run: sh ressources/dmotion/py/nessma/nessma.sh

      - name: setup git config
        run: |
          git config user.name "nessma bot"
          git config user.email "<>"

      - name: commit
        run: |
          git pull
          git add ressources/dmotion/py/nessma/nessma.m3u8
          git commit -m "nessma updated"
          git push origin master
