name: nrj action

on:
  schedule:
    - cron: '02 */20 * * *'
  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "nrj bot"
      
      - name: Install requests module
        run: |
          python -m pip install --upgrade pip
          pip install requests
      
      - name: Run Python script
        run: |
          python ressources/rtlm6/nrj12.py ressources/rtlm6/nrj12.m3u8 ressources/rtlm6/cherie25.m3u8
        
      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull origin master
          git commit -m "nrj updated"
          git push origin master
