name: rtpall

on:
  schedule:
    - cron: '14 */12 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: config
        run: |
          git config --global user.email "<>"
          git config --global user.name "rtpall bot"

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          
      - name: Install requests module
        run: python3 -m pip install requests streamlink

      - name: fetch content rtpall
        run: |
          python3 ressources/tvipt/py/rtp1.py > ressources/tvipt/py/rtp1.m3u8 &&
          python3 ressources/tvipt/py/rtp2.py > ressources/tvipt/py/rtp2.m3u8 &&
          python3 ressources/tvipt/py/rtp3.py > ressources/tvipt/py/rtp3.m3u8 &&
          python3 ressources/tvipt/py/rtp4.py > ressources/tvipt/py/rtp4.m3u8

      - name: git add
        run: |
          git add -A
          ls -la 
          
      - name: commit & push
        run: |
          git pull
          git commit -m "rtpall updated"
          git push
