# Thanks to LITUATUI user on github
name: tvi-pt action
on:
  schedule:
    - cron: "00 04,16 * * *"
    
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: updating tvi-pt
        run: sh ressources/tvipt/sh/tvipt.sh

      - name: setup git config
        run: |
          git config user.name "tvi-pt bot"
          git config user.email "<>"
      - name: commit
        run: |
          git pull
          git add all.m3u
          git commit -m "tvi-pt updated"
          git push origin master
