name: tvi-pt_ch action
on:
  schedule:
    - cron: "00 04,16 * * *"
    
  workflow_dispatch:

jobs:
  update-stream:
    runs-on: ubuntu-latest
    steps:
    
      - name: checkout
        uses: actions/checkout@v3

      - name: updating tvi-pt_ch
        run: sh ressources/tvipt/sh/tviptch.sh

      - name: setup git config
        run: |
          git config user.name "tvi-pt_ch bot"
          git config user.email "<>"
          
      - name: commit
        run: |
          git pull
          git add ressources/tvipt/sh/cnnpt.m3u8
          git add ressources/tvipt/sh/tvi.m3u8
          git add ressources/tvipt/sh/tviint.m3u8
          git commit -m "tvi-pt_ch updated"
          git push origin master
